AWSTemplateFormatVersion: '2010-09-09'
Description: CloudFormation Template with Dynamic Parameter

Parameters:
  Region:
    Type: String
    Default: us-west-2
    Description: AWS region for the resources
    AllowedValues:
      - us-east-1
      - us-west-2
      - eu-west-1

Resources:
  S3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Join [ "-", [!Ref Region, "my-bucket"]]