AWSTemplateFormatVersion: '2010-09-09'
Description: CloudFormation Template with Default Values and Constraints

Parameters:
  InstanceType:
    Description: EC2 instance type for the server
    Type: String
    Default: t2.micro
    AllowedValues:
      - t2.micro
      - t2.small
      - m5.large
    ConstraintDescription: Must be a valid EC2 instance type.

  SSHKeyName:
    Description: Name of the existing EC2 key pair for SSH access
    Type: AWS::EC2::KeyPair::KeyName
    Default: bitsohio
    ConstraintDescription: Must be an existing EC2 key pair name.

Resources:
  EC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: !Ref InstanceType
      KeyName: !Ref SSHKeyName
      ImageId: ami-069d73f3235b535bd   # Replace with your desired AMI ID